from pydantic import BaseModel, EmailStr, conint
# Import BaseModel from Pydantic to create schemas for validation
# NOTE: BaseModel automatically handles type checking and validation

from datetime import datetime
# Import datetime to handle timestamp fields
# NOTE: Useful for created_at or other date/time fields

from typing import Optional, Annotated
# Import Optional for optional type hints
# NOTE: Used for fields that can be None



class UserOut(BaseModel):
    # Schema for returning user data (response model)
    # NOTE: Used when sending user info back to client

    id: int
    # User ID from database
    # NOTE: Auto-generated by DB

    email: EmailStr
    # User email address
    # NOTE: Password is intentionally NOT included

    created_at: datetime
    # Account creation timestamp
    # NOTE: Set automatically by the database

    class Config:
        orm_mode = True
        # Enables returning SQLAlchemy ORM objects
        # NOTE: Required for FastAPI response models



# Pydantic model to define the structure of Post data
class Post(BaseModel):
    # Base schema for Post (used in request body)
    # NOTE: Used for creating or updating posts

    title: str
    # Title field of type string
    # NOTE: Missing or wrong type → FastAPI returns 422 automatically

    content: str
    # Content field of type string
    # NOTE: Also validated by Pydantic

    published: bool = True
    # Published field with default True
    # NOTE: If client does not send this, it defaults to True


# Response model to control what is returned to the client
class PostResp(Post):
    # Schema used for responses
    # NOTE: Includes extra fields like id and created_at

    id: int
    # ID of the post returned from database
    # NOTE: Not required when creating post

    created_at: datetime
    # Timestamp of post creation
    # NOTE: Typically set by the database automatically

    owner_id: int
    # ID of the user who owns the post

    owner: UserOut

    class Config:
        orm_mode = True
        # Enables returning SQLAlchemy ORM objects directly
        # NOTE: Required if you want to return ORM models in FastAPI


class PostOut(BaseModel):
    Post: PostResp
    votes: int

    class Config:
        orm_mode = True


class UserCreate(BaseModel):
    # Schema for creating a new user (request body)
    # NOTE: Used during user registration

    email: EmailStr
    # User email field with email validation
    # NOTE: EmailStr automatically checks valid email format

    password: str
    # User password in plain text (input only)
    # NOTE: This should be hashed before saving to database




class UserLogin(BaseModel):
    # Schema for user login (request body)
    # NOTE: Used during authentication

    email: EmailStr
    # Email used to log in
    # NOTE: Must match a registered user

    password: str
    # Plain password provided by user
    # NOTE: Will be verified against hashed password


class Token(BaseModel):
    # Schema for authentication token response
    # NOTE: Returned after successful login

    token: str
    # JWT access token string
    # NOTE: Client stores this token for future requests

    token_type: str
    # Token type (usually "bearer")
    # NOTE: Used in Authorization header


class TokenData(BaseModel):
    # Schema for token payload data
    # NOTE: Used internally when decoding JWT

    id: Optional[int] = None
    # User ID extracted from token
    # NOTE: Optional because token may be invalid or missing data


# NOTE: Never return passwords in response schemas
# NOTE: Separate schemas for Create / Login / Output (best practice)
# NOTE: EmailStr provides built-in email validation
# NOTE: Token and TokenData are part of JWT authentication flow


class Vote(BaseModel):
    post_id: int
    dir: Annotated[int, conint(le=1, ge=0)]  # Example: 0 or 1 only